tec_user_index:
    path:     /
    defaults: { _controller: TecUserBundle:User:index }
tec_user_contact:
    path:     /contact
    defaults: { _controller: TecUserBundle:User:contact }
#HOW
tec_user_how:
    path:     /comment_ça_marche
    defaults: { _controller: TecUserBundle:User:how }        
    
