#tec_user_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: TecUserBundle:Default:index }
tec_user_contact:
    path:     /contact
    defaults: { _controller: TecUserBundle:User:contact }