tec_user_index:
    path:     /
    defaults: { _controller: TecUserBundle:User:index }
tec_user_contact:
    path:     /contact
    defaults: { _controller: TecUserBundle:User:contact }
#HOW
tec_user_how:
    path:     /comment_ça_marche
    defaults: { _controller: TecUserBundle:User:how }   
    
#PUBLIC PROFILE
tec_user_profile:
    path:     /user/{id}
    defaults: { _controller: TecUserBundle:User:profile } 
    
#NOTIFICATION
tec_user_updatenotification:
    path:     /user/notification/update/{id}
    defaults: { _controller: TecUserBundle:User:updateNotification } 
    
tec_user_delnotification:
    path:     /user/notification/del/{id}
    defaults: { _controller: TecUserBundle:User:delNotification } 
    

    
