<?php

namespace Tec\ServiceBundle\Entity;

/**
 * PosterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosterRepository extends \Doctrine\ORM\EntityRepository
{
}
