<?php

namespace Tec\ServiceBundle\Entity;

/**
 * Sub_categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sub_categorieRepository extends \Doctrine\ORM\EntityRepository
{
}
