<?php

namespace Tec\UserBundle\Entity;

/**
 * AddresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddresseRepository extends \Doctrine\ORM\EntityRepository
{
}
