<?php

namespace Tec\UserBundle\Entity;

/**
 * DemanderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemanderRepository extends \Doctrine\ORM\EntityRepository
{
}
