<?php

namespace Tec\UserBundle\Entity;

/**
 * FournirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournirRepository extends \Doctrine\ORM\EntityRepository
{
}
