#tec_service_homepage:
#    path:     /
#    defaults: { _controller: TecServiceBundle:Default:index }
tec_service_resultspage:
    path:     /results
    defaults: { _controller: TecServiceBundle:Service:results }
    
#ANNONCE
tec_service_addannonce:
    path:     /addannonce
    defaults: { _controller: TecServiceBundle:Service:addAnnonce }